baseURL = "https://ai-prompt.devops-playground.dev"
title = "AI Prompt Playground"
defaultContentLanguage = "en"

[module]
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"

[params]
  copyright = "yarencheng"
  privacy_policy = "https://policies.google.com/privacy"

[params.ui]
  sidebar_menu_compact = false
  sidebar_menu_foldable = false

[languages]
  [languages.en]
    contentDir = "content/en"
    title = "AI Prompt Playground"
    languageName ="English"
    weight = 1
